apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: football-prediction-models-pvc
  namespace: football-prediction
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: hcloud-volumes